# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69f125a8c34b1137ebb923641721661f42bc8997ee06c5adee76bb362c5b3931dc707f7e2ab8a38ad2978d64b14e02af9d20810ea7764ecd5b10a33579bbb9a1

test:
  secret_key_base: 8432ca1c4276bdeedbf98a3ffad8c4fffde289db45d58e3dcecfce4f849a0d338e9cd0ff2cb8f22d623f5cfd596dd57642c950e8b6ea020ae2330a8ca1b58fd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
